const players = [
    // INDIA
    { id: 1, name: "Rohit Sharma", country: "India", role: "Batter", batting: 95, bowling: 10, overall: 94 },
    { id: 2, name: "Virat Kohli", country: "India", role: "Batter", batting: 98, bowling: 5, overall: 97 },
    { id: 3, name: "Shubman Gill", country: "India", role: "Batter", batting: 92, bowling: 5, overall: 91 },
    { id: 4, name: "Yashasvi Jaiswal", country: "India", role: "Batter", batting: 91, bowling: 5, overall: 90 },
    { id: 5, name: "KL Rahul", country: "India", role: "Batter", batting: 89, bowling: 5, overall: 88 },
    { id: 6, name: "Rishabh Pant", country: "India", role: "Wicketkeeper", batting: 91, bowling: 5, overall: 90 },
    { id: 7, name: "Sanju Samson", country: "India", role: "Wicketkeeper", batting: 88, bowling: 5, overall: 87 },
    { id: 8, name: "Suryakumar Yadav", country: "India", role: "Batter", batting: 94, bowling: 5, overall: 92 },
    { id: 9, name: "Shreyas Iyer", country: "India", role: "Batter", batting: 87, bowling: 10, overall: 86 },
    { id: 10, name: "Rinku Singh", country: "India", role: "Batter", batting: 88, bowling: 5, overall: 86 },
    { id: 11, name: "Hardik Pandya", country: "India", role: "All-rounder", batting: 88, bowling: 82, overall: 88 },
    { id: 12, name: "Ravindra Jadeja", country: "India", role: "All-rounder", batting: 84, bowling: 91, overall: 90 },
    { id: 13, name: "Axar Patel", country: "India", role: "All-rounder", batting: 80, bowling: 88, overall: 86 },
    { id: 14, name: "Ravichandran Ashwin", country: "India", role: "All-rounder", batting: 70, bowling: 91, overall: 86 },
    { id: 15, name: "Jasprit Bumrah", country: "India", role: "Bowler", batting: 25, bowling: 99, overall: 98 },
    { id: 16, name: "Mohammed Shami", country: "India", role: "Bowler", batting: 25, bowling: 92, overall: 90 },
    { id: 17, name: "Mohammed Siraj", country: "India", role: "Bowler", batting: 20, bowling: 87, overall: 85 },
    { id: 18, name: "Kuldeep Yadav", country: "India", role: "Bowler", batting: 25, bowling: 90, overall: 88 },
    { id: 19, name: "Yuzvendra Chahal", country: "India", role: "Bowler", batting: 20, bowling: 86, overall: 84 },
    { id: 20, name: "Arshdeep Singh", country: "India", role: "Bowler", batting: 20, bowling: 86, overall: 84 },

    // AUSTRALIA
    { id: 21, name: "Steve Smith", country: "Australia", role: "Batter", batting: 94, bowling: 10, overall: 92 },
    { id: 22, name: "David Warner", country: "Australia", role: "Batter", batting: 93, bowling: 5, overall: 91 },
    { id: 23, name: "Travis Head", country: "Australia", role: "Batter", batting: 94, bowling: 20, overall: 92 },
    { id: 24, name: "Marnus Labuschagne", country: "Australia", role: "Batter", batting: 88, bowling: 15, overall: 86 },
    { id: 25, name: "Glenn Maxwell", country: "Australia", role: "All-rounder", batting: 92, bowling: 72, overall: 90 },
    { id: 26, name: "Mitchell Marsh", country: "Australia", role: "All-rounder", batting: 86, bowling: 78, overall: 85 },
    { id: 27, name: "Cameron Green", country: "Australia", role: "All-rounder", batting: 82, bowling: 80, overall: 83 },
    { id: 28, name: "Pat Cummins", country: "Australia", role: "Bowler", batting: 60, bowling: 94, overall: 91 },
    { id: 29, name: "Mitchell Starc", country: "Australia", role: "Bowler", batting: 45, bowling: 95, overall: 92 },
    { id: 30, name: "Josh Hazlewood", country: "Australia", role: "Bowler", batting: 20, bowling: 94, overall: 91 },
    { id: 31, name: "Adam Zampa", country: "Australia", role: "Bowler", batting: 20, bowling: 88, overall: 86 },
    { id: 32, name: "Alex Carey", country: "Australia", role: "Wicketkeeper", batting: 78, bowling: 5, overall: 77 },
    { id: 33, name: "Josh Inglis", country: "Australia", role: "Wicketkeeper", batting: 84, bowling: 5, overall: 82 },
    { id: 34, name: "Matthew Short", country: "Australia", role: "All-rounder", batting: 80, bowling: 65, overall: 78 },
    { id: 35, name: "Marcus Stoinis", country: "Australia", role: "All-rounder", batting: 84, bowling: 70, overall: 82 },

    // ENGLAND
    { id: 36, name: "Joe Root", country: "England", role: "Batter", batting: 96, bowling: 20, overall: 94 },
    { id: 37, name: "Jos Buttler", country: "England", role: "Wicketkeeper", batting: 94, bowling: 5, overall: 92 },
    { id: 38, name: "Harry Brook", country: "England", role: "Batter", batting: 91, bowling: 5, overall: 89 },
    { id: 39, name: "Ben Duckett", country: "England", role: "Batter", batting: 88, bowling: 5, overall: 85 },
    { id: 40, name: "Liam Livingstone", country: "England", role: "All-rounder", batting: 89, bowling: 76, overall: 87 },
    { id: 41, name: "Ben Stokes", country: "England", role: "All-rounder", batting: 91, bowling: 84, overall: 91 },
    { id: 42, name: "Moeen Ali", country: "England", role: "All-rounder", batting: 82, bowling: 80, overall: 82 },
    { id: 43, name: "Sam Curran", country: "England", role: "All-rounder", batting: 80, bowling: 82, overall: 81 },
    { id: 44, name: "Jofra Archer", country: "England", role: "Bowler", batting: 30, bowling: 91, overall: 89 },
    { id: 45, name: "Mark Wood", country: "England", role: "Bowler", batting: 25, bowling: 90, overall: 87 },
    { id: 46, name: "Adil Rashid", country: "England", role: "Bowler", batting: 25, bowling: 88, overall: 85 },
    { id: 47, name: "Reece Topley", country: "England", role: "Bowler", batting: 20, bowling: 80, overall: 78 },
    { id: 48, name: "Phil Salt", country: "England", role: "Wicketkeeper", batting: 90, bowling: 5, overall: 87 },
    { id: 49, name: "Jonny Bairstow", country: "England", role: "Wicketkeeper", batting: 86, bowling: 5, overall: 84 },
    { id: 50, name: "Dawid Malan", country: "England", role: "Batter", batting: 86, bowling: 5, overall: 83 },

    // SOUTH AFRICA
    { id: 51, name: "Quinton de Kock", country: "South Africa", role: "Wicketkeeper", batting: 92, bowling: 5, overall: 90 },
    { id: 52, name: "Aiden Markram", country: "South Africa", role: "All-rounder", batting: 88, bowling: 75, overall: 86 },
    { id: 53, name: "Heinrich Klaasen", country: "South Africa", role: "Wicketkeeper", batting: 94, bowling: 5, overall: 91 },
    { id: 54, name: "David Miller", country: "South Africa", role: "Batter", batting: 90, bowling: 5, overall: 87 },
    { id: 55, name: "Temba Bavuma", country: "South Africa", role: "Batter", batting: 80, bowling: 5, overall: 78 },
    { id: 56, name: "Rassie van der Dussen", country: "South Africa", role: "Batter", batting: 87, bowling: 5, overall: 84 },
    { id: 57, name: "Marco Jansen", country: "South Africa", role: "All-rounder", batting: 78, bowling: 87, overall: 84 },
    { id: 58, name: "Kagiso Rabada", country: "South Africa", role: "Bowler", batting: 35, bowling: 94, overall: 91 },
    { id: 59, name: "Anrich Nortje", country: "South Africa", role: "Bowler", batting: 20, bowling: 88, overall: 85 },
    { id: 60, name: "Tabraiz Shamsi", country: "South Africa", role: "Bowler", batting: 20, bowling: 84, overall: 82 },
    { id: 61, name: "Gerald Coetzee", country: "South Africa", role: "Bowler", batting: 25, bowling: 85, overall: 82 },
    { id: 62, name: "Keshav Maharaj", country: "South Africa", role: "Bowler", batting: 40, bowling: 86, overall: 83 },
    { id: 63, name: "Reeza Hendricks", country: "South Africa", role: "Batter", batting: 82, bowling: 5, overall: 79 },
    { id: 64, name: "Donovan Ferreira", country: "South Africa", role: "Wicketkeeper", batting: 84, bowling: 55, overall: 80 },
    { id: 65, name: "Wiaan Mulder", country: "South Africa", role: "All-rounder", batting: 76, bowling: 78, overall: 77 },

    // NEW ZEALAND
    { id: 66, name: "Kane Williamson", country: "New Zealand", role: "Batter", batting: 94, bowling: 10, overall: 92 },
    { id: 67, name: "Devon Conway", country: "New Zealand", role: "Wicketkeeper", batting: 90, bowling: 5, overall: 87 },
    { id: 68, name: "Daryl Mitchell", country: "New Zealand", role: "All-rounder", batting: 87, bowling: 72, overall: 85 },
    { id: 69, name: "Rachin Ravindra", country: "New Zealand", role: "All-rounder", batting: 86, bowling: 76, overall: 84 },
    { id: 70, name: "Glenn Phillips", country: "New Zealand", role: "All-rounder", batting: 88, bowling: 70, overall: 84 },
    { id: 71, name: "Finn Allen", country: "New Zealand", role: "Batter", batting: 87, bowling: 5, overall: 83 },
    { id: 72, name: "Tom Latham", country: "New Zealand", role: "Wicketkeeper", batting: 82, bowling: 5, overall: 80 },
    { id: 73, name: "Mitchell Santner", country: "New Zealand", role: "All-rounder", batting: 75, bowling: 86, overall: 82 },
    { id: 74, name: "Trent Boult", country: "New Zealand", role: "Bowler", batting: 35, bowling: 94, overall: 91 },
    { id: 75, name: "Tim Southee", country: "New Zealand", role: "Bowler", batting: 45, bowling: 88, overall: 85 },
    { id: 76, name: "Lockie Ferguson", country: "New Zealand", role: "Bowler", batting: 20, bowling: 87, overall: 84 },
    { id: 77, name: "Matt Henry", country: "New Zealand", role: "Bowler", batting: 30, bowling: 88, overall: 85 },
    { id: 78, name: "Ish Sodhi", country: "New Zealand", role: "Bowler", batting: 25, bowling: 82, overall: 79 },
    { id: 79, name: "Will Young", country: "New Zealand", role: "Batter", batting: 82, bowling: 5, overall: 79 },
    { id: 80, name: "Mark Chapman", country: "New Zealand", role: "All-rounder", batting: 79, bowling: 65, overall: 77 },

    // PAKISTAN
    { id: 81, name: "Babar Azam", country: "Pakistan", role: "Batter", batting: 96, bowling: 5, overall: 94 },
    { id: 82, name: "Mohammad Rizwan", country: "Pakistan", role: "Wicketkeeper", batting: 91, bowling: 5, overall: 89 },
    { id: 83, name: "Fakhar Zaman", country: "Pakistan", role: "Batter", batting: 88, bowling: 5, overall: 85 },
    { id: 84, name: "Mohammad Haris", country: "Pakistan", role: "Wicketkeeper", batting: 82, bowling: 5, overall: 79 },
    { id: 85, name: "Saim Ayub", country: "Pakistan", role: "Batter", batting: 84, bowling: 20, overall: 81 },
    { id: 86, name: "Salman Ali Agha", country: "Pakistan", role: "All-rounder", batting: 78, bowling: 68, overall: 76 },
    { id: 87, name: "Shadab Khan", country: "Pakistan", role: "All-rounder", batting: 82, bowling: 82, overall: 82 },
    { id: 88, name: "Imad Wasim", country: "Pakistan", role: "All-rounder", batting: 72, bowling: 82, overall: 78 },
    { id: 89, name: "Shaheen Afridi", country: "Pakistan", role: "Bowler", batting: 25, bowling: 94, overall: 91 },
    { id: 90, name: "Haris Rauf", country: "Pakistan", role: "Bowler", batting: 20, bowling: 89, overall: 86 },
    { id: 91, name: "Naseem Shah", country: "Pakistan", role: "Bowler", batting: 25, bowling: 90, overall: 87 },
    { id: 92, name: "Mohammad Amir", country: "Pakistan", role: "Bowler", batting: 20, bowling: 87, overall: 84 },
    { id: 93, name: "Abrar Ahmed", country: "Pakistan", role: "Bowler", batting: 20, bowling: 83, overall: 80 },
    { id: 94, name: "Usama Mir", country: "Pakistan", role: "Bowler", batting: 20, bowling: 80, overall: 77 },
    { id: 95, name: "Iftikhar Ahmed", country: "Pakistan", role: "All-rounder", batting: 75, bowling: 65, overall: 73 },

    // SRI LANKA
    { id: 96, name: "Kusal Mendis", country: "Sri Lanka", role: "Wicketkeeper", batting: 86, bowling: 5, overall: 83 },
    { id: 97, name: "Pathum Nissanka", country: "Sri Lanka", role: "Batter", batting: 88, bowling: 5, overall: 85 },
    { id: 98, name: "Charith Asalanka", country: "Sri Lanka", role: "Batter", batting: 84, bowling: 55, overall: 81 },
    { id: 99, name: "Kusal Perera", country: "Sri Lanka", role: "Wicketkeeper", batting: 84, bowling: 5, overall: 81 },
    { id: 100, name: "Dhananjaya de Silva", country: "Sri Lanka", role: "All-rounder", batting: 82, bowling: 75, overall: 80 },
    { id: 101, name: "Wanindu Hasaranga", country: "Sri Lanka", role: "All-rounder", batting: 76, bowling: 91, overall: 86 },
    { id: 102, name: "Angelo Mathews", country: "Sri Lanka", role: "All-rounder", batting: 75, bowling: 70, overall: 73 },
    { id: 103, name: "Dasun Shanaka", country: "Sri Lanka", role: "All-rounder", batting: 78, bowling: 68, overall: 75 },
    { id: 104, name: "Maheesh Theekshana", country: "Sri Lanka", role: "Bowler", batting: 35, bowling: 85, overall: 82 },
    { id: 105, name: "Matheesha Pathirana", country: "Sri Lanka", role: "Bowler", batting: 20, bowling: 91, overall: 87 },
    { id: 106, name: "Dushmantha Chameera", country: "Sri Lanka", role: "Bowler", batting: 20, bowling: 84, overall: 81 },
    { id: 107, name: "Dilshan Madushanka", country: "Sri Lanka", role: "Bowler", batting: 20, bowling: 84, overall: 81 },
    { id: 108, name: "Jeffrey Vandersay", country: "Sri Lanka", role: "Bowler", batting: 20, bowling: 80, overall: 77 },
    { id: 109, name: "Dunith Wellalage", country: "Sri Lanka", role: "All-rounder", batting: 72, bowling: 80, overall: 76 },
    { id: 110, name: "Kamindu Mendis", country: "Sri Lanka", role: "All-rounder", batting: 80, bowling: 72, overall: 78 },

    // WEST INDIES
    { id: 111, name: "Nicholas Pooran", country: "West Indies", role: "Wicketkeeper", batting: 94, bowling: 5, overall: 91 },
    { id: 112, name: "Shai Hope", country: "West Indies", role: "Wicketkeeper", batting: 86, bowling: 5, overall: 83 },
    { id: 113, name: "Brandon King", country: "West Indies", role: "Batter", batting: 83, bowling: 5, overall: 80 },
    { id: 114, name: "Evin Lewis", country: "West Indies", role: "Batter", batting: 87, bowling: 5, overall: 83 },
    { id: 115, name: "Shimron Hetmyer", country: "West Indies", role: "Batter", batting: 84, bowling: 5, overall: 81 },
    { id: 116, name: "Rovman Powell", country: "West Indies", role: "All-rounder", batting: 82, bowling: 65, overall: 78 },
    { id: 117, name: "Andre Russell", country: "West Indies", role: "All-rounder", batting: 91, bowling: 86, overall: 90 },
    { id: 118, name: "Jason Holder", country: "West Indies", role: "All-rounder", batting: 78, bowling: 86, overall: 82 },
    { id: 119, name: "Romario Shepherd", country: "West Indies", role: "All-rounder", batting: 78, bowling: 78, overall: 77 },
    { id: 120, name: "Akeal Hosein", country: "West Indies", role: "Bowler", batting: 55, bowling: 85, overall: 80 },
    { id: 121, name: "Alzarri Joseph", country: "West Indies", role: "Bowler", batting: 25, bowling: 87, overall: 83 },
    { id: 122, name: "Obed McCoy", country: "West Indies", role: "Bowler", batting: 20, bowling: 80, overall: 77 },
    { id: 123, name: "Gudakesh Motie", country: "West Indies", role: "Bowler", batting: 25, bowling: 82, overall: 79 },
    { id: 124, name: "Johnson Charles", country: "West Indies", role: "Wicketkeeper", batting: 82, bowling: 5, overall: 78 },
    { id: 125, name: "Kyle Mayers", country: "West Indies", role: "All-rounder", batting: 84, bowling: 72, overall: 80 },

    // BANGLADESH
    { id: 126, name: "Shakib Al Hasan", country: "Bangladesh", role: "All-rounder", batting: 86, bowling: 91, overall: 89 },
    { id: 127, name: "Litton Das", country: "Bangladesh", role: "Wicketkeeper", batting: 84, bowling: 5, overall: 81 },
    { id: 128, name: "Najmul Hossain Shanto", country: "Bangladesh", role: "Batter", batting: 82, bowling: 5, overall: 79 },
    { id: 129, name: "Towhid Hridoy", country: "Bangladesh", role: "Batter", batting: 78, bowling: 20, overall: 75 },
    { id: 130, name: "Mushfiqur Rahim", country: "Bangladesh", role: "Wicketkeeper", batting: 84, bowling: 5, overall: 81 },
    { id: 131, name: "Mahmudullah", country: "Bangladesh", role: "All-rounder", batting: 78, bowling: 65, overall: 76 },
    { id: 132, name: "Mehidy Hasan Miraz", country: "Bangladesh", role: "All-rounder", batting: 76, bowling: 84, overall: 80 },
    { id: 133, name: "Mustafizur Rahman", country: "Bangladesh", role: "Bowler", batting: 20, bowling: 87, overall: 83 },
    { id: 134, name: "Taskin Ahmed", country: "Bangladesh", role: "Bowler", batting: 20, bowling: 85, overall: 81 },
    { id: 135, name: "Nasum Ahmed", country: "Bangladesh", role: "Bowler", batting: 20, bowling: 79, overall: 76 },

    // AFGHANISTAN
    { id: 136, name: "Rahmanullah Gurbaz", country: "Afghanistan", role: "Wicketkeeper", batting: 88, bowling: 5, overall: 84 },
    { id: 137, name: "Ibrahim Zadran", country: "Afghanistan", role: "Batter", batting: 84, bowling: 5, overall: 81 },
    { id: 138, name: "Rahmat Shah", country: "Afghanistan", role: "Batter", batting: 80, bowling: 5, overall: 77 },
    { id: 139, name: "Azmatullah Omarzai", country: "Afghanistan", role: "All-rounder", batting: 80, bowling: 82, overall: 80 },
    { id: 140, name: "Mohammad Nabi", country: "Afghanistan", role: "All-rounder", batting: 76, bowling: 84, overall: 80 },
    { id: 141, name: "Gulbadin Naib", country: "Afghanistan", role: "All-rounder", batting: 72, bowling: 76, overall: 73 },
    { id: 142, name: "Rashid Khan", country: "Afghanistan", role: "All-rounder", batting: 78, bowling: 96, overall: 91 },
    { id: 143, name: "Mujeeb Ur Rahman", country: "Afghanistan", role: "Bowler", batting: 25, bowling: 88, overall: 84 },
    { id: 144, name: "Fazalhaq Farooqi", country: "Afghanistan", role: "Bowler", batting: 20, bowling: 86, overall: 82 },
    { id: 145, name: "Naveen-ul-Haq", country: "Afghanistan", role: "Bowler", batting: 20, bowling: 85, overall: 81 },

    // IRELAND
    { id: 146, name: "Paul Stirling", country: "Ireland", role: "All-rounder", batting: 86, bowling: 55, overall: 81 },
    { id: 147, name: "Harry Tector", country: "Ireland", role: "Batter", batting: 82, bowling: 15, overall: 78 },
    { id: 148, name: "Lorcan Tucker", country: "Ireland", role: "Wicketkeeper", batting: 78, bowling: 5, overall: 74 },
    { id: 149, name: "Andrew Balbirnie", country: "Ireland", role: "Batter", batting: 79, bowling: 5, overall: 75 },
    { id: 150, name: "Curtis Campher", country: "Ireland", role: "All-rounder", batting: 76, bowling: 72, overall: 74 },

    // ENGLAND / INTERNATIONAL
    { id: 151, name: "Rehan Ahmed", country: "England", role: "All-rounder", batting: 65, bowling: 76, overall: 72 },
    { id: 152, name: "Jacob Bethell", country: "England", role: "All-rounder", batting: 78, bowling: 72, overall: 75 },
    { id: 153, name: "Will Jacks", country: "England", role: "All-rounder", batting: 87, bowling: 65, overall: 81 },
    { id: 154, name: "Tom Banton", country: "England", role: "Wicketkeeper", batting: 82, bowling: 5, overall: 78 },
    { id: 155, name: "Jamie Smith", country: "England", role: "Wicketkeeper", batting: 83, bowling: 5, overall: 79 },

    // AUSTRALIA / INTERNATIONAL
    { id: 156, name: "Jake Fraser-McGurk", country: "Australia", role: "Batter", batting: 88, bowling: 5, overall: 82 },
    { id: 157, name: "Nathan Ellis", country: "Australia", role: "Bowler", batting: 20, bowling: 82, overall: 79 },
    { id: 158, name: "Sean Abbott", country: "Australia", role: "All-rounder", batting: 72, bowling: 80, overall: 76 },
    { id: 159, name: "Cooper Connolly", country: "Australia", role: "All-rounder", batting: 75, bowling: 68, overall: 72 },
    { id: 160, name: "Xavier Bartlett", country: "Australia", role: "Bowler", batting: 25, bowling: 83, overall: 79 },

    // INDIA DOMESTIC
    { id: 161, name: "Abhishek Sharma", country: "India", role: "All-rounder", batting: 90, bowling: 65, overall: 86 },
    { id: 162, name: "Tilak Varma", country: "India", role: "Batter", batting: 88, bowling: 35, overall: 84 },
    { id: 163, name: "Ishan Kishan", country: "India", role: "Wicketkeeper", batting: 87, bowling: 5, overall: 83 },
    { id: 164, name: "Ruturaj Gaikwad", country: "India", role: "Batter", batting: 89, bowling: 5, overall: 85 },
    { id: 165, name: "Sanat Sangwan", country: "India", role: "Batter", batting: 74, bowling: 5, overall: 70 },
    { id: 166, name: "Nitish Rana", country: "India", role: "All-rounder", batting: 82, bowling: 60, overall: 77 },
    { id: 167, name: "Venkatesh Iyer", country: "India", role: "All-rounder", batting: 83, bowling: 58, overall: 77 },
    { id: 168, name: "Shivam Dube", country: "India", role: "All-rounder", batting: 85, bowling: 62, overall: 80 },
    { id: 169, name: "Washington Sundar", country: "India", role: "All-rounder", batting: 72, bowling: 84, overall: 79 },
    { id: 170, name: "Deepak Chahar", country: "India", role: "Bowler", batting: 55, bowling: 80, overall: 76 },
    { id: 171, name: "Avesh Khan", country: "India", role: "Bowler", batting: 20, bowling: 82, overall: 79 },
    { id: 172, name: "Mukesh Kumar", country: "India", role: "Bowler", batting: 20, bowling: 80, overall: 77 },
    { id: 173, name: "T Natarajan", country: "India", role: "Bowler", batting: 20, bowling: 84, overall: 80 },
    { id: 174, name: "Bhuvneshwar Kumar", country: "India", role: "Bowler", batting: 35, bowling: 84, overall: 81 },
    { id: 175, name: "Umran Malik", country: "India", role: "Bowler", batting: 20, bowling: 81, overall: 76 },

    // MORE INTERNATIONAL
    { id: 176, name: "Sikandar Raza", country: "Zimbabwe", role: "All-rounder", batting: 82, bowling: 78, overall: 80 },
    { id: 177, name: "Sean Williams", country: "Zimbabwe", role: "All-rounder", batting: 80, bowling: 80, overall: 78 },
    { id: 178, name: "Blessing Muzarabani", country: "Zimbabwe", role: "Bowler", batting: 20, bowling: 83, overall: 79 },
    { id: 179, name: "Ryan Burl", country: "Zimbabwe", role: "All-rounder", batting: 73, bowling: 72, overall: 70 },
    { id: 180, name: "David Wiese", country: "Namibia", role: "All-rounder", batting: 76, bowling: 78, overall: 75 },
    { id: 181, name: "Gerhard Erasmus", country: "Namibia", role: "All-rounder", batting: 76, bowling: 75, overall: 74 },
    { id: 182, name: "Bas de Leede", country: "Netherlands", role: "All-rounder", batting: 72, bowling: 76, overall: 72 },
    { id: 183, name: "Scott Edwards", country: "Netherlands", role: "Wicketkeeper", batting: 78, bowling: 5, overall: 74 },
    { id: 184, name: "Mark Watt", country: "Scotland", role: "Bowler", batting: 30, bowling: 80, overall: 75 },
    { id: 185, name: "George Munsey", country: "Scotland", role: "Batter", batting: 82, bowling: 5, overall: 77 },

    // ADDITIONAL STARS
    { id: 186, name: "Faf du Plessis", country: "South Africa", role: "Batter", batting: 88, bowling: 5, overall: 85 },
    { id: 187, name: "Dale Steyn", country: "South Africa", role: "Bowler", batting: 20, bowling: 96, overall: 91 },
    { id: 188, name: "AB de Villiers", country: "South Africa", role: "Wicketkeeper", batting: 97, bowling: 5, overall: 95 },
    { id: 189, name: "Chris Gayle", country: "West Indies", role: "Batter", batting: 95, bowling: 50, overall: 91 },
    { id: 190, name: "Kieron Pollard", country: "West Indies", role: "All-rounder", batting: 88, bowling: 78, overall: 84 },
    { id: 191, name: "Lasith Malinga", country: "Sri Lanka", role: "Bowler", batting: 15, bowling: 95, overall: 91 },
    { id: 192, name: "Kumar Sangakkara", country: "Sri Lanka", role: "Wicketkeeper", batting: 94, bowling: 5, overall: 91 },
    { id: 193, name: "Mahela Jayawardene", country: "Sri Lanka", role: "Batter", batting: 92, bowling: 5, overall: 89 },
    { id: 194, name: "Brian Lara", country: "West Indies", role: "Batter", batting: 98, bowling: 5, overall: 95 },
    { id: 195, name: "Muttiah Muralitharan", country: "Sri Lanka", role: "Bowler", batting: 20, bowling: 99, overall: 95 },
    { id: 196, name: "Jacques Kallis", country: "South Africa", role: "All-rounder", batting: 95, bowling: 93, overall: 94 },
    { id: 197, name: "Shane Warne", country: "Australia", role: "Bowler", batting: 25, bowling: 97, overall: 93 },
    { id: 198, name: "Ricky Ponting", country: "Australia", role: "Batter", batting: 95, bowling: 5, overall: 92 },
    { id: 199, name: "Wasim Akram", country: "Pakistan", role: "Bowler", batting: 45, bowling: 98, overall: 94 },
    { id: 200, name: "Sachin Tendulkar", country: "India", role: "Batter", batting: 99, bowling: 65, overall: 98 }
];


module.exports = players;